import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar/Navbar";
import { getSession } from "@/lib/auth";
import AuthProvider from "@/providers/AuthProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AlertProvider from "@/providers/AlertProvider";
const poppins = Poppins({
  subsets: ['latin'],
  display: "swap",
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});
export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <AuthProvider session={session}>
          <Navbar />
            {children}
            <AlertProvider/>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
